# Generated by Django 3.1.4 on 2020-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201207_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='publisher',
            field=models.CharField(default='Anonymous', max_length=50, verbose_name='Публикатор'),
        ),
    ]
